# Generated by Django 4.1.1 on 2022-09-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_candidate_gender_alter_education_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
