# Generated by Django 4.1.1 on 2022-09-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_candidate_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
