# Generated by Django 4.1.1 on 2022-09-09 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_candidate_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='first_name',
            new_name='fname',
        ),
    ]
