# Generated by Django 4.1.1 on 2022-09-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_rename_first_name_candidate_fname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='fname',
            new_name='first_name',
        ),
    ]
