# Generated by Django 4.1.1 on 2022-10-11 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_candidate_applied_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='applied_on',
            field=models.DateField(default=datetime.datetime(2022, 10, 11, 12, 19, 9, 593508, tzinfo=datetime.timezone.utc)),
        ),
    ]
